version: '3.8'
# docker volume（データを永続的に保存できるようにする仕組み）の作成
volumes:
  docker-volume:

# 各コンテナの設定
services:
  # Webサーバーコンテナ
  web:
    build: ./docker/vue
    ports:
      - '8080:8080'
    # 先にappサーバーコンテナを起動する
    depends_on:
      - app
    # コンテナの標準入力をオープンしたままにする
    stdin_open: true
    # ローカルとコンテナのファイル共有
    volumes:
      - ./src:/usr/src/app
  # Appサーバーコンテナ
  app:
    build: ./docker/python
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/src/app
  # DBサーバーコンテナ
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - docker-volume:/var/lib/mysql
